name: Swift Tests

# Trigger on pull requests and pushes to main
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # (Optional) Cache dependencies, if your project uses them

      # Run Xcode tests
      - name: Run Tests
        run: |
          xcodebuild clean test \
            -scheme "Scheme_for_test" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
            -quiet
